name: VoodooTalismans
version: 1.0
main: wbe.voodooTalismans.VoodooTalismans
api-version: 1.21
author: wbe
depend: [AcuaticLostWealth, YggdrasilsBark, TartarusRiches]
commands:
  VoodooTalismans:
    description: VoodooTalismans main command
    aliases: [vt, voodoot, vtalismans]
    permission: voodootalismans.command
